name: Publish Wheels to PyPI

on:
  workflow_run:
    workflows: ["Build Wheels"]
    types:
      - completed

jobs:
  publish-to-pypi:
    name: Publish Wheels to PyPI
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist-artifacts

      - name: Combine wheels
        run: |
          mkdir -p dist
          find ./dist-artifacts -type f -name "*.whl" -exec cp {} dist/ \;
          find ./dist-artifacts -type f -name "*.tar.gz" -exec cp {} dist/ \;

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
