name: Build Wheels

on:
  release:
    types: [created]

jobs:

  build-wheels:
    name: Build Wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Install GCC and OpenMP (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libomp-dev

      - name: Install GCC (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gcc
          GCC_VERSION=$(brew list gcc | grep -Eo 'gcc-[0-9]+' | head -1 | grep -Eo '[0-9]+')
          echo "CC=$(brew --prefix)/bin/gcc-$GCC_VERSION" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix)/bin/g++-$GCC_VERSION" >> $GITHUB_ENV
      - name: Build libomp from source (macOS)
        if: runner.os == 'macOS'
        run: |
          git clone https://github.com/llvm/llvm-project.git --depth=1
          cd llvm-project
          mkdir build-libomp && cd build-libomp
          cmake ../openmp -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/libomp-universal
          make -j$(sysctl -n hw.logicalcpu)
          make install
          echo "LDFLAGS=-L$HOME/libomp-universal/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$HOME/libomp-universal/include" >> $GITHUB_ENV
          echo "REPAIR_LIBRARY_PATH=$HOME/libomp-universal/lib" >> $GITHUB_ENV
      - name: Set cibuildwheel archs (macOS)
        if: runner.os == 'macOS'
        run: echo "CIBW_ARCHS_MACOS=universal2" >> $GITHUB_ENV
      - name: Set cibuildwheel repair command (macOS)
        if: runner.os == 'macOS'
        run: echo "CIBW_REPAIR_WHEEL_COMMAND_MACOS=DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel numpy pybind11 scipy

      - name: Build wheels with cibuildwheel
        run: |
          cibuildwheel --output-dir wheelhouse

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          path: ./wheelhouse/*.whl

  publish-to-pypi:
    name: Publish Wheels to PyPI
    needs: build-wheels
    environment: pypi
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Gather wheels
        run: |
          find dist/ -type f -name "*.whl" -exec mv {} dist/ \;
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
