name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  build-and-pypi-publish:
    name: Build and Publish Wheels to PyPI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Install GCC and OpenMP (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libomp-dev

      - name: Install GCC (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gcc libomp
          GCC_VERSION=$(brew list gcc | grep -Eo 'gcc-[0-9]+' | head -1 | grep -Eo '[0-9]+')
          echo "CC=$(brew --prefix)/bin/gcc-$GCC_VERSION" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix)/bin/g++-$GCC_VERSION" >> $GITHUB_ENV
          echo "LDFLAGS=-L/opt/homebrew/opt/libomp/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/opt/homebrew/opt/libomp/include" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install numpy pybind11 scipy

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel  # Could also be python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
